name: Build TOP Fitness 2.0

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar proyecto
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Descomprimir proyecto
        run: unzip -q TOP_Fitness_2.0_JStudio.zip -d project

      - name: Instalar Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.2'

      - name: Compilar APK
        working-directory: project/topj
        run: gradle assembleDebug --no-daemon

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: TOP-Fitness-2.0-APK
          path: project/topj/app/build/outputs/apk/debug/*.apk
